# Generated by Django 5.0.1 on 2024-04-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narupedia_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='image',
        ),
        migrations.RemoveField(
            model_name='village',
            name='image',
        ),
    ]
